name: PR

on:
  create:
    tags:
      - v*
      
jobs:
  show_tag:
    name: 'Show tag'
    runs-on: ubuntu-latest
    env:
      GITUB_TAG: ${{ github.event.ref }}
    steps:
      - name: Echo
        run: echo -e ${GITUB_TAG#v}
            
